/** Authored teaching UI; observations and source are filled through text properties. */
export function technicalMarkup(): string {
	return `<aside id="technical-panel" class="technical-panel" aria-labelledby="technical-heading" hidden>
		<header class="technical-heading"><h2 id="technical-heading" tabindex="-1">Integration workspace</h2><button type="button" id="back-to-invoice" class="quiet-button">Back to invoice</button></header>
		<div class="technical-invoice"><div><strong id="technical-invoice-name"></strong><p id="technical-invoice-outcome"></p></div><button type="button" id="technical-pay" class="primary-button">Try this payment</button></div>
		<p class="technical-intro">Follow one payment across two applications. Each step shows the actual observed data and the code that handles it.</p>
		<ol class="handoff-steps" aria-label="Integration steps">
		${["Pip provides props", "Harbor becomes ready", "Harbor reports the result", "Pip acknowledges", "Payment window closes"].map((label, index) => `<li><button type="button" data-step="${index}" aria-pressed="${index === 0}"><span>${label}</span><small id="step-status-${index}">Not observed</small></button></li>`).join("")}
		</ol>
		<section class="step-evidence" aria-labelledby="step-heading"><h3 id="step-heading" tabindex="-1"></h3><p id="step-description"></p><p id="step-observed" role="status"></p><pre class="technical-json" tabindex="0" aria-label="Selected step data"><code id="step-data"></code></pre><p id="step-source-label" class="source-filename"></p><pre class="source-code step-code" tabindex="0" aria-label="Selected step source"><code id="step-code"></code></pre></section>
		<details class="technical-details"><summary>Connection details</summary><dl class="connection-meta"><div><dt>Pip Veterinary · Consumer</dt><dd id="consumer-origin"></dd></div><div><dt>Harbor Pay · Host</dt><dd id="provider-origin"></dd></div><div><dt>Payment window</dt><dd id="connection-context"></dd></div><div><dt>Window lifecycle</dt><dd id="connection-phase"></dd></div></dl></details>
		<details class="technical-details" id="full-evidence"><summary>Full props, callbacks and event history</summary><h3>Current invoice props</h3><pre class="technical-json" tabindex="0" aria-label="Full props"><code id="live-props"></code></pre><h3>Remote callbacks</h3><div class="callback-row"><code>onReady()</code><span id="onReady-calls">0 calls</span></div><div class="callback-row"><code>onResult(result)</code><span id="onResult-calls">0 calls</span></div><pre class="technical-json" tabindex="0" aria-label="Last callback"><code id="callback-payload">No callback yet.</code></pre><ol id="integration-events" class="integration-events" tabindex="0" aria-label="Integration event history"><li>Take a payment to see events.</li></ol></details>
		<details class="technical-details" id="full-source"><summary>Complete application source</summary><div class="source-tabs" role="group" aria-label="Source file"><button type="button" data-source="consumer" aria-pressed="true">Consumer</button><button type="button" data-source="provider" aria-pressed="false">Host</button><button type="button" data-source="contract" aria-pressed="false">Shared contract</button><button type="button" data-source="acceptance" aria-pressed="false">Merchant rules</button><button type="button" data-source="simulation" aria-pressed="false">Demo processor</button></div><div class="source-jumps" role="group" aria-label="Jump to integration code"><button type="button" data-jump="create">create</button><button type="button" data-jump="initHost">initHost</button><button type="button" data-jump="onResult">onResult</button><button type="button" data-jump="acknowledgement">Acknowledgement</button></div><p id="source-filename" class="source-filename"></p><pre class="source-code" tabindex="0" aria-label="Complete source"><code id="technical-code"></code></pre></details>
		<p class="technical-note">Only receipt metadata returns to Pip. Card number, expiry and CVC stay in Harbor. These are application observations, not wire-protocol logs.</p>
	</aside>`;
}
