export const TEST_SCENARIO_IDS = [
  'lifecycle',
  'security',
  'bridge',
  'props',
  'controls',
  'nested',
  'errors',
  'configuration',
  'instances',
  'host-controls',
  'transport',
  'reliability',
  'common-actions',
  'redirect',
  'timeout-recovery',
  'stress',
  'popup',
  'checkout-e2e',
] as const;
